<!-- The content created automatically -->
<div class="row">

  <div class="col-4 mb-3">
    <div class="card">
      <img class="card-img-top" src="<?php echo $this->baseUrl('/assets/artista/johnny-cash.jpg'); ?>" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">Johnny Cash</h5>
        <p class="card-text">
          I keep a close watch on this heart of mine
          <br/>
          I keep my eyes wide...
        </p>
        <a href="<?php echo $this->baseUrl('/album?id=johnny-cash'); ?>" class="btn btn-primary">Ver músicas</a>
      </div>
    </div>
  </div>

  <div class="col-4 mb-3">
    <div class="card">
      <img class="card-img-top" src="<?php echo $this->baseUrl('/assets/artista/natiruts.jpg'); ?>" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">Natiruts</h5>
        <p class="card-text">Quero te mostrar um mundo novo de cores...</p>
        <a href="<?php echo $this->baseUrl('/album?id=natiruts'); ?>" class="btn btn-primary">Ver músicas</a>
      </div>
    </div>
  </div>

  <div class="col-4 mb-3">
    <div class="card">
      <img class="card-img-top" src="<?php echo $this->baseUrl('/assets/artista/ac-dc.jpg'); ?>" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">AC DC</h5>
        <p class="card-text">
          This is black in black
          <br/>
          This is AC DC!
        </p>
        <a href="<?php echo $this->baseUrl('/album?id=ac-dc'); ?>" class="btn btn-primary">Ver músicas</a>
      </div>
    </div>
  </div>

  <div class="col-4 mb-3">
    <div class="card">
      <img class="card-img-top" src="<?php echo $this->baseUrl('/assets/artista/bob-marley.jpg'); ?>" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">Bob Marley</h5>
        <p class="card-text">
          Africa UNITE!
          <br/>
          Get Up, Stand up!
        </p>
        <a href="<?php echo $this->baseUrl('/album?id=bob-marley'); ?>" class="btn btn-primary">Ver músicas</a>
      </div>
    </div>
  </div>

</div>
