
<div class="row">
  <?php if ($artists): ?>
    <?php foreach($artists as $item): ?>
      <div class="col-4 mb-3">
        <div class="card">
          <!--<img class="card-img-top" src="<?php echo $this->basePath('/assets/artista/johnny-cash.jpg'); ?>" alt="Card image cap">-->
          <div class="card-body">
            <h5 class="card-title"><?php echo $item['name']; ?></h5>
            <a href="<?php echo $this->baseUrl(); ?>/albums/<?php echo $item['pk_artist']; ?>/<?php echo strtolower(toDashCase($item['name'])); ?>.html" class="btn btn-primary">Ver músicas</a>
          </div>
        </div>
      </div>
    <?php endforeach; ?>
  <?php endif; ?>

</div>
