<hr/>
<h3>
  #<?php echo $this->getParam('id'); ?>
  - <?php echo strtoupper(str_replace('-', ' ', $this->getParam('name'))); ?>
</h3>

<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Nome</th>
      <th scope="col">Duração</th>
      <th scope="col" style="width: 100px;"></th>
    </tr>
  </thead>
  <tbody>
    <?php for($i=1; $i<=10; $i++): ?>
      <tr>
        <td scope="row">#<?php echo $i; ?></td>
        <td>Nome da musica</td>
        <td>3:52</td>
        <td class="text-center">
          <a href="#" class="btn btn-sm btn-danger"><i class="fa fa-trash-alt"></i></a>
        </td>
      </tr>
    <?php endfor; ?>
  <tbody>
</table>
