<hr/>
<h3>
  #<?php echo $this->getParam('id'); ?>
  - <?php echo strtoupper(str_replace('-', ' ', $this->getParam('name'))); ?>
</h3>

<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th scope="col" style="width: 100px;"></th>
      <th scope="col">Nome</th>
      <th scope="col">Ano</th>
      <th scope="col">Duração</th>
    </tr>
  </thead>
  <tbody>
    <?php for($i=1; $i<=10; $i++): ?>
      <tr>
        <td scope="row">#<?php echo $i; ?></td>
        <td>Nome da musica</td>
        <td>1965</td>
        <td>3:52</td>
      </tr>
    <?php endfor; ?>
  <tbody>
</table>
